# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\x12\x04\x61uth\"+\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"5\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"J\n\x0cUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"R\n\x13OnlineUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.auth.User\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"G\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\xa1\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tfirstName\x18\x04 \x01(\t\x12\x10\n\x08lastName\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\x12\x18\n\x04role\x18\x07 \x01(\x0b\x32\n.auth.Role\x12\x10\n\x08isOnline\x18\x08 \x01(\x08\x12\x10\n\x08lastSeen\x18\t \x01(\t\"5\n\x04Role\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x9a\x02\n\x0b\x41uthService\x12\x37\n\x0bGetUserById\x12\x14.auth.GetUserRequest\x1a\x12.auth.UserResponse\x12\x41\n\x0eGetUserByEmail\x12\x1b.auth.GetUserByEmailRequest\x1a\x12.auth.UserResponse\x12\x45\n\x1bGetOnlineCustomerSupporters\x12\x0b.auth.Empty\x1a\x19.auth.OnlineUsersResponse\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=26
  _globals['_GETUSERREQUEST']._serialized_end=69
  _globals['_GETUSERBYEMAILREQUEST']._serialized_start=71
  _globals['_GETUSERBYEMAILREQUEST']._serialized_end=124
  _globals['_USERRESPONSE']._serialized_start=126
  _globals['_USERRESPONSE']._serialized_end=200
  _globals['_ONLINEUSERSRESPONSE']._serialized_start=202
  _globals['_ONLINEUSERSRESPONSE']._serialized_end=284
  _globals['_VALIDATETOKENREQUEST']._serialized_start=286
  _globals['_VALIDATETOKENREQUEST']._serialized_end=323
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=325
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=396
  _globals['_USER']._serialized_start=399
  _globals['_USER']._serialized_end=560
  _globals['_ROLE']._serialized_start=562
  _globals['_ROLE']._serialized_end=615
  _globals['_EMPTY']._serialized_start=617
  _globals['_EMPTY']._serialized_end=624
  _globals['_AUTHSERVICE']._serialized_start=627
  _globals['_AUTHSERVICE']._serialized_end=909
# @@protoc_insertion_point(module_scope)
