version: "3.8"
services:
  mongodb_auth_service:
    image: mongo:latest
    container_name: mongodb_auth_service
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth-service
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mongodb-network

  # MongoDB Admin UI (Opsional)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "5000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb_auth_service:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb_auth_service
    networks:
      - mongodb-network
    restart: always

volumes:
  mongodb_data:

networks:
  mongodb-network:
    driver: bridge 