services:
  api-gateway:
    build: .
    container_name: api_gateway
    ports:
      - "${PORT}:9000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - TICKET_SERVICE_URL=${TICKET_SERVICE_URL}
      - CHOKIDAR_USEPOLLING=true
      - NODEMON_POLLING=true
    networks:
      - mongodb-network
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src

networks:
  mongodb-network:
    external: true
