services:
  redis_auth_service:
    image: redis:latest
    container_name: redis_auth_service
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./data:/data
    networks:
      - mongodb-network
    command: redis-server --appendonly yes

  # Redis Admin UI (Opsional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    ports:
      - "5002:8081"
    environment:
      - REDIS_HOSTS=local:redis_auth_service:6379
    depends_on:
      - redis_auth_service
    networks:
      - mongodb-network
    restart: always

volumes:
  redis_data:

networks:
  mongodb-network:
    driver: bridge 