services:
  redis_service:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    volumes:
      - ./data:/data
    networks:
      - mongodb-network
    command: redis-server --appendonly yes

  # Redis Admin UI (Opsiyonel)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${REDIS_COMMANDER_CONTAINER_NAME}
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    environment:
      - REDIS_HOSTS=${REDIS_COMMANDER_HOSTS}
    depends_on:
      - redis_service
    networks:
      - mongodb-network
    restart: always

volumes:
  redis_data:

networks:
  mongodb-network:
    external: true